<div class="row margin-bottom-10">
    <div class="col-md-2">
        <a href="/book/<?php echo $this->book->getId(); ?>">
            <img class="media-object" src="<?php echo $this->book->getImage(); ?>" alt="<?php echo $this->book->getTitle(); ?>"
                 style="height: 300px;">
        </a>
    </div>
    <div class="col-md-10">
        <h4>
            <a href="/book/<?php echo $this->book->getId(); ?>">
                <?php echo $this->book->getTitle(); ?>
            </a>
        </h4>
        <h6>
            <a href="/author/<?php echo $this->book->getAuthor()->getId(); ?>">
                <?php echo $this->book->getAuthor()->getName(); ?>
            </a>
        </h6>
        <p>
            <?php echo $this->book->getDescription(); ?>
        </p>
        <?php if ($this->book->getPdf()) : ?>
            <p>
                <a href="<?php echo $this->book->getPdf(); ?>" class="btn btn-info btn-xs" target="_blank">
                    Download PDF file
                </a>
            </p>
        <?php endif; ?>
        <?php if ($this->book->getGenres()) : ?>
            <p>
                <?php foreach ($this->book->getGenres() as $genre) : ?>
                    <a href="/genre/<?php echo $genre->getId(); ?>" class="btn btn-primary btn-xs">
                        <?php echo $genre->getName() ?>
                    </a>
                <?php endforeach; ?>
            </p>
        <?php endif; ?>
    </div>
</div>
