<div class="row">
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-home"></i> Dashboard <span>> Add Genre</span>
        </h1>
    </div>
</div>

<div class="row">
<div class="col-sm-12">
<form action="<?php echo $this->url("admin-action", array("action" => "save-genre")); ?>" method="post" class="ajaxForm">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-sortable">
            <header role="heading">
                <h2><strong>Genre Fields</strong></h2>
                <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
            </header>
            <div role="content">
                <div class="widget-body padding-10">
                    <div class="smart-form">
                        <section>
                            <label class="label" for="genre_name">Name</label>
                            <label class="input">
                                <input type="text" id="genre_name" name="genre_name" />
                            </label>
                        </section>
                        <section>
                            <button type="submit" class="triggers_if_this_element_in_viewport btn btn-lg btn-success">
                                Save Genre
                            </button>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
</div>
